server:
  host: "proxy.example.com"
  address: ":9243"
  tls:
    email: "admin@example.com"
    enabled: false
    useLetsEncrypt: true
    certificatePath: ""
    privateKeyPath: ""

proxy:
  lycan:
    scheme: "https"
    host: "lycan.rentivo.com"

  elasticsearch:
    scheme: "https"
    host: "localhost:9243"

logging:
  level: "error"

  credentials:
    scheme: "https"
    host: "localhost:9243"
    username: "elastic"
    password: "password"

  elasticsearchQueries:
    index: "test-es-queries"
    logBufferSize: 20
    queryDebounceDuration: "3000ms"

  lycanPriceRequests:
    index: "test-price-requests"
    logBufferSize: 20
    queryDebounceDuration: "3000ms"