server:
  host: "proxy.example.com"
  address: ":9243"
  tls:
    email: "admin@example.com"
    enabled: false
    useLetsEncrypt: true
    certificatePath: ""
    privateKeyPath: ""

proxy:
  elasticsearch:
    scheme: "https"
    host: "localhost:9243"

logging:
  level: "error"
  elasticsearch:
    scheme: "https"
    host: "localhost:9243"
    index: "query-log-index"
    username: "elastic"
    password: "password"
    logBufferSize: 20
    queryDebounceDuration: "3000ms"